### ISSUE TITLE
Can't export mesh after processing. Orcawave support

### ISSUE THREAD

**Issue by rahulcr33** [BEMRosetta/BEMRosetta#11]
Hello,

I imported a geometry from Gmsh and changed the COG using the 'process' tab in 'Mesh Handling'. Then I exported the mesh into the Nemoh.dat format. The change in COG is not reflected on the new file created. How can I solve this ?

Please help. 

Thanks.

**Comment by izabala123** [comment]
Hello Rahul

The problem is that the .dat format of Nemoh meshes does not include the position of the centre of gravity, so when saving in this format, this data is not recorded.
However, what could be done is, together with the .dat, and if there is sufficient information, to save the file "Hydrostatics.dat", that is supported in Nemoh, containing the centre of gravity, centre of buoyancy and submerged volume. Is this what would work for you?

Best regards
Iñaki

**Comment by rahulcr33** [comment]
Hi Iñaki, thanks for the tip. This seems to be working.

BEMRosetta is a wonderful tool. It would be nice if it can read Orcaflex/Orcawave results too :) Thank you so much.

**Comment by izabala123** [comment]
Hello Rahul

In the next commit, BEMRosetta will load and save "Hydrostatics.dat" at the same time as it reads the .dat file. In this way, the centre of buoyancy, the centre of gravity and the submerged volume will also be managed together with the Nemoh mesh.

What do you mean by "it would be nice if it can read Orcaflex/Orcawave results too". Can you define this a bit more?

Iñaki

**Comment by rahulcr33** [comment]
That would be great if you can include this feature.

I use BEMRosetta for comparing the results from Aqwa, Wamit and Nemoh. Additionally I use Orcawave which is a popular software from Orcina. It can perform diffraction analysis and compute added mass, damping coefficients, RAOs etc. Later these results are used in Orcaflex for mooring analyses, wind turbines etc in the time domain. These softwares are very popular in the offshore industry. At the moment I compare the added mass, damping coefficients, RAOs etc. separately when I use Orcaflex/Orcawave.  If BEMRosetta can read the result files of Orcawave and Orcaflex that will be so useful for the maritime community.

Thank you,

Rahul.

**Comment by izabala123** [comment]
Thank you Rahul for your nice words

What you propose is interesting. If you want, you can help me with little effort on your part. Is that OK with you?

Iñaki

**Comment by rahulcr33** [comment]
For sure, I can help :)

**Comment by izabala123** [comment]
Hi Rahul

Soon Orcawave will be supported for loading. If you still are interested you may test it.

Best regards
Iñaki

**Comment by rahulcr33** [comment]
That's great, thanks for the update.
