### ISSUE TITLE
About hydro coeff in BEMRosetta 

### ISSUE THREAD

**Issue by Dylan0824** [BEMRosetta/BEMRosetta#13]
Hi,
I am using Nemoh and BEM Rosetta for my work. I need to check the excitation force in BEMRosetta. But when i creat two bodied or more in nemoh and after running in Neomh i want to see the results in BEMRosetta, i cant see the results about the second body. It turns about zero all the time.
Kindly help.
![facd67052181e47639059c9bc14a572](https://user-images.githubusercontent.com/115965311/196082563-848a50f6-4eee-4e8b-ae5d-993eee53a44b.png)

**Comment by izabala123** [comment]
Hi Dylan

You are right. There was an inexcusable error. It has been corrected. Please check if you can read your file correctly.

Iñaki
