### ISSUE TITLE
Import results from Capytaine

### ISSUE THREAD

**Issue by Dadidal** [BEMRosetta/BEMRosetta#14]
Good afternoon! I have a problem when trying to open .tec results from Capytaine.
I try to compare results calculated in AQWA and Capytaine. AQWA results were imported without any problems.
When I tried to import Capytaine results (.tec files) I obtained error, that results have to be located in "results" folder. Then I moved my files to "results" folder and got an Error "Nemoh.cal can't be found". After that, I used "BEM Solver" to generate all solver files for Capytaine from AQWA files and then copied my .tec files to "results" folder. Finally I got an Error:
`Error: [File: 'C:\Users\dadid\Documents\August Explorer\Working folder\BEM comparison\Test\Results\RadiationCoefficients.tec', line: 614]: No data available`
Please help me to resolve this issue. I attached necessary files.
[Test.zip](https://github.com/BEMRosetta/BEMRosetta/files/10361225/Test.zip)

**Comment by izabala123** [comment]
Hello Dadidal

Thank you for your report and for including sample files. 👍 

About the last error, it seems that Capytaine has changed a little the file format for the 'RadiationCoefficients.tec' files, so, I have changed BEMRosetta to handle that.

For the first errors, BEMRosetta expects this file structure, that I have seen repeatedly in the different Nemoh versions, including the very last v3 from last December:
Model folder
- Nemoh.cal
- Input.txt
- mesh/
    - mesh.dat
- results/
    - ExcitationForce.tec
    -  RadiationCoefficients.tec

Please if you expect other structure please tell me to adapt BEMRosetta.

Best regards
Iñaki

**Comment by Dadidal** [comment]
Good afternoon! Thank you for your help with Capytaine! Now it works.

Yesterday I created input files for HAMS using BEM rosetta and calculated the problem in the latest version of HAMS. But when I tried to import the results of the calculation (hydrodynamic coefficients and forces) I got the following error:

```
Error: [File: 'C:\Users\dadid\Documents\August Explorer\Working folder\BEM comparison_adjusted\0.010\HAMS\Output\Wamit_format\Buoy.4', line: 1]: 
Wrong format in Wamit file 'C:\Users\dadid\Documents\August Explorer\Working folder\BEM comparison_adjusted\0.010\HAMS\Output\Wamit_format\Buoy.1'
```
I attach files here:
[HAMS.zip](https://github.com/BEMRosetta/BEMRosetta/files/10407413/HAMS.zip)

**Comment by Dadidal** [comment]
Oh sorry, everything works fine if you define Mass/Inertia matrix before the calculation. I set all matrix terms to 0 and that was the problem

**Comment by izabala123** [comment]
Hi Dadidal

Yes, HAMS withstood with the problem, but filling the .4 file with NaN, so BEMRosetta complained because she doesn't like them :blush::

![image](https://user-images.githubusercontent.com/38589221/215412601-087374d6-2592-4720-8c99-6bc6c6f0c688.png)

Iñaki
