### ISSUE TITLE
Export drift forces from AQWA to WAMIT

### ISSUE THREAD

**Issue by Dadidal** [BEMRosetta/BEMRosetta#15]
Good afternoon!
Is it possible somehow to include drift forces to WANIT .out during the conversion of AQWA results to the WAMIT output file? I want to include drift forces in my time-domain calculations in WEC-Sim software but WEC-Sim can read drift forces only from WAMIT. I calculated the BEM problem in AQWA and tried to convert AQWA results to the WAMIT .out file using BEM Rosetta. But the final .out file does not include drift forces calculated in AQWA.
I attach my AQWA results here 
[Analysis.zip](https://github.com/BEMRosetta/BEMRosetta/files/10532766/Analysis.zip)

**Comment by izabala123** [comment]
Hi Dadidal

Yes, you are right. Now BEMRosetta loads drift from .out, but it does not save it.
It will be included soon.

Iñaki

**Comment by izabala123** [comment]
Hi Dadidal

Now the saved .out includes the drift forces. Please check it.

Best regards
Iñaki
