### ISSUE TITLE
Phase invertion QTF from AQWA to WAMIT

### ISSUE THREAD

**Issue by burripamp** [BEMRosetta/BEMRosetta#16]
Hello! 

first of all  thanks for this nice work! 

I have one question( potentially bug?) regarding the import and export of AQWA data. 

When exporting data from AQWA to WAMIT , I have seen that the linear excitation phases are changed ( - )  .  I believe this is because the different wave definitions in the two codes.  
But then when exporting 12s and 12d files from AQWA QTF data,  I think the phases are not being inverted by the code . Is that the case  - is there a reason for that or is it potentially a bug ? 

Many thanks in advance! 
Armando

**Comment by izabala123** [comment]
Hi Burripamp

I have been thinking about this issue for quite some time, and I believe that in this case Occam's razor is true... the simplest solution is the most accurate one. It is just fixed. Thank you!

Iñaki

**Comment by izabala123** [comment]
Problem solved.
