### ISSUE TITLE
Problem in The Hydrodynamic Coefficient

### ISSUE THREAD

**Issue by dith96** [BEMRosetta/BEMRosetta#21]
Dear @izabala123 

I am an undergraduate student and currently working on my final project. I am trying to model an OWC cylinder using Nemoh, but I can't see the results of K, Kirf, RAO, QTF and others on BEMRosetta.

like this,
![image](https://user-images.githubusercontent.com/126154503/229985977-25a45260-1d33-40cc-ae8b-409851f2d6a0.png)

Only a few results that I can see. I need RAO data but it doesn't appear in BEMRosetta. do you know where the problem is? i hope you can help me. Thank you..

Best Regards, 
Dith

**Comment by izabala123** [comment]
Hi Dith

Please tell me which version of Nemoh you are using, and it would also be great if you could send me all the files. 
As far as I remember, the classic version of Nemoh does not directly get the hydrostatic stiffness and RAO, it does not get the QTF, and the IRF requires setting certain parameters.

Best regards
Iñaki

**Comment by dith96** [comment]
Dear @izabala123 

First, I'm using Nemoh v1.0-beta, but the result for freesurface is NaN. I do not know why.
[Silinder OWC.zip](https://github.com/BEMRosetta/BEMRosetta/files/11165692/Silinder.OWC.zip)

Secondly, I tried using Nemoh v3.0.1 (actually I'm still confused about this version, I'm still learning). From this version i got result for freesurface. Nothing is NaN anymore. But when I open in BEMRosetta, RAO, QTF and other values don't show up.
[1_Cylinder.zip](https://github.com/BEMRosetta/BEMRosetta/files/11165713/1_Cylinder.zip)

Maybe something went wrong when I input the data, but I still don't know where the error is. The modeling results of the two versions are also different, including the results displayed on BEMRosetta are also different. Even though it's the same case.

I hope you will help me. Thank you very much.

Best Regards,
Dith

**Comment by izabala123** [comment]
Hello Dith

Unfortunately, modelling an OWC is a relatively complex case even with Wamit, and you would need special support. Compassis SeaFEM has a great support of water columns, and a free license for a month for students, but it also requires expert advice to prepare OWC.
In addition, it is reported that Nemoh, at least with v1, doesn't handle properly OWC. HAMS solver cannot handle OWC too.

I am very sorry, but if you don't have a solver able to handle OWC, and an expert to help you, I advise you to choose other geometry for your project.

![image](https://user-images.githubusercontent.com/38589221/230316608-2ac19452-49ac-486d-a972-e98d4e73425f.png)

Best regards
Iñaki

**Comment by izabala123** [comment]
Hi Dith

I know the authors of this study personally, as well as some of the authors of Nemoh, and we have discussed this issue. They are experts of the highest level on the subject. I myself have worked professionally with OWC. The experience with Nemoh is that it does not work well in calculating the interaction of several rigid bodies, nor does it work well with a sub-case of it, which is the OWC simulation. If you want, you can give my contact details to your teacher so that she can talk to me.

Best regards
Iñaki

**Comment by dith96** [comment]
Dear @izabala123 

Thank you, Sir..
Do you have another alternative how to do my project? I want to compare my analytical and numerical modeling results. For numerical method I use Nemoh.

I will also notify my lecturer soon, and ask permission to give you her contact. Thank you very much you want to help me.

But sorry in advance, tomorrow is Good Friday, most likely my lecturer will not attend to my message. So, maybe I'll take a little longer. But I will let you know as soon as I can.
Thank you..

Best Regards,
Dith

**Comment by izabala123** [comment]
No rush, I'm not moving from here :blush:

**Comment by dith96** [comment]
Dear, @izabala123 

Thank you very much, Sir..
May I know your contact? So I can give it to my lecturer?
And maybe tomorrow, I can give my lecturer's contact.

Best Regards,
Dith

**Comment by izabala123** [comment]
No problem, you can get one contact [here](https://marineenergyjournal.org/imej/article/view/114/58).

**Comment by dith96** [comment]
Dear @izabala123 

Thank you very much, Sir..

Best Regards,
Dith
