### ISSUE TITLE
Converting Nemoh output with Python

### ISSUE THREAD

**Issue by KlootwijkBart** [BEMRosetta/BEMRosetta#22]
Dear @izabala123 , 

For my master thesis, I am using OpenFAST and Nemoh in the loop to simulate various floating platform designs for offshore wind application, with Python. I use the pyfast toolbox from OpenFAST, and I've converted the Nemoh matlab wrapper to a Python version, which I've adjusted slightly to suit my own needs. 

To use the hydrodynamic coefficients in OpenFAST's HydroDyn module, I need to convert the Nemoh output files to WAMIT .1, .3 and .hst format. I understand that this is possible with BEMRosetta; however I need to do it inside a Python loop, so I can't be using a GUI.

What are the possibilities for this with BEMRosetta, and what would be the best approach? 

Awaiting your kind advice, 

Bart Klootwijk

**Comment by izabala123** [comment]
Hi Bart

The easiest way would be using bemrosetta_cl.exe. It is a command line version.

Running from inside python this command line, would do the job:

bemrosetta_cl -bem -i "Your path\nemoh.cal" -c "newfile.1"

You don't need to put all the extensions .1, .3, ... WIth .1 it will save as much Wamit files as possible extracted form Nemoh files.

Command line interface is much more developed than python one, but if you require it, just tell me. All features are available in a common core, so it would be easy to make them available to python (not all at once, please :blush:).

Best regards
Iñaki

**Comment by KlootwijkBart** [comment]
Many thanks Iñaki, your suggestion works wonderfully!

Although perhaps an extended python library for BEMRosetta would be a good upgrade, for me this solution will do just fine for my application. 

Best regards,
Bart

**Comment by izabala123** [comment]
I am pleased.

**Comment by KlootwijkBart** [comment]
Dear @izabala123, 

I have an additional question. 

I am trying to understand how the zero (A0)- and infinite-frequency (Ainf) added mass coefficients are calculated, which make up the first rows in the WAMIT .1 file. 

I understand that these are the asymptotic values of the added mass coefficient at zero frequency and zero wave period. 

According to the Nemoh manual, the infinite frequency added mass matrix is calculated using the impulse response function in the post-processing module, and is saved in the "IRF.tec" results file. However, when I look at the file and compare the values with those of Ainf in the Hydro Coeff tab of the BEMRosetta GUI, I notice that they are not exactly the same. 

As for the zero frequency added mass, this is not provided by Nemoh (it is mentioned nowhere in the manual). But it is computed by BEMRosetta in the conversion from Nemoh to a WAMIT .1file

I tried to search for the procedures of calculating A0 and Ainf in the source code, but as I am not familiar with c++, I wasn't able to find/understand how it's done. The goal is to validate A0 and Ainf of my Nemoh simulation results with data from WAMIT simulations. Please could you help/guide me with this?

If you require any additional information or a description of the results please let me know. 

Best regards, 
Bart

**Comment by izabala123** [comment]
Hi Bart

By default if A0 doesn't exist it tries to guess it. The method is a quadratic interpolation, so it is really an extrapolation from closest values. If the Ainf you see in BEMRosetta is different to the one in the text files, it is probably because either the gravity or the density are not the same. If this is not the case, I beg you to send me a sample case to see what happens.

best regards
Iñaki

**Comment by KlootwijkBart** [comment]
Hi Iñaki, 

Thank you for your quick response, 

I am not sure what goes wrong. As far as I know the values of gravity and density should be the same: 9.81 and 1025.0 respectively (standard values used for the test cases of Nemoh). 

Maybe a bit of extra context helps. I am using Nemoh to model the hydrodynamic coefficients of a semi-submersible platform design, which I will use with OpenFAST. To verify that my BEM modelling approach is correct, I created the mesh of the OC4 DeepCWind platform (using numpy and the aximesh and mesh functions of Nemoh) and simulated its hydrodynamic response with Nemoh, such that I could validate the results against the data available from the OpenFAST r-tests of the same theoretical OC4 semisub (https://github.com/OpenFAST/r-test/tree/main/glue-codes/openfast/5MW_Baseline/HydroData). 

I converted the Nemoh results to the WAMIT file format using the approach suggested in your previous post, but when I compare the values of **Ainf** between the original Nemoh file and the converted .1 file, they do not match. The principal entries of the matrix are shown in the two pictures below.

I will send you my Nemoh files via e-mail; I hope the problem is clear and there is a simple explanation for it.
I appreciate your help a lot!

Data as processed by BEMRosetta:
![image](https://user-images.githubusercontent.com/61149223/235611400-93ba9da4-ad3c-47a4-a919-ae7ece4f23e7.png)
Data from Nemoh results (IRF.tec file):
![image](https://user-images.githubusercontent.com/61149223/235611683-2dd2dd65-01ed-465d-ba7c-fe5ccd7efb98.png)

**Comment by izabala123** [comment]
Excellent!. 

Please consider that one of the main goals of BEMRosetta is to compare. Some parameters are difficult to match, for example, calculations with different water depths. However, different gravity, density, or even centre of reference, can be changed, so data from different sources can be properly compared.

Best regards
Iñaki

**Comment by izabala123** [comment]
I have just got your results, set the right density and gravity, and voilà!
![image](https://user-images.githubusercontent.com/38589221/236470969-9bae13b9-730b-4483-805f-d1cc0be988eb.png)

**Comment by chenkongenvision** [comment]
Hi, @KlootwijkBart and @izabala123 

I am also using BEMRosetta to convert NEMOH's results into WAMIT format as OpenFAST/HydroDyn's inputs. I've successfully got *.1, *.2, *.3, *.hst files to run OpenFAST. But I am wondering that if BEMRosetta can convert NEMOH's QTF results into WAMIT format (*.12 and etc.)? If yes, then I can enable 2nd order floating platform forces in OpenFAST's simulation. 

I tried a bit times, but failed to even load NEMOH's QTF results in BEMRosetta. Do I make some mistakes here? Sorry I don't find any manual of BEMRosetta.

Thanks in advance!

Best regards,
Chen

**Comment by chenkongenvision** [comment]
Thanks Bart, it will be great if you can share your approach. 

In my case, it's important to get the 2nd-order hydrodynamic effect, but I get no fund to buy WAMIT or AWQA license. NEMOH seems my only choice so far, and I have to make a conversion from NEMOH to WAMIT results because of OpenFAST. 
 
Best regards,
Chen

**Comment by KlootwijkBart** [comment]
Hi @chenkongenvision , 

If you give me your contact info, I can send you the part of my Python code that takes care of the QTF files conversion. Please note that I'm not a software developer and I haven't tested my code against other applications than my own project :) 

If it doesn't work directly for you, it should at least show the methods used for extracting the NEMOH files and writing it to a .12d and .12s file

Best, Bart

**Comment by chenkongenvision** [comment]
You can find my email address [here](https://github.com/chenkongenvision). Many thanks, @KlootwijkBart !

Best regards,
Chen

**Comment by izabala123** [comment]
Hi all

How many messages! I haven't tried to include the qtf files from Nemoh's last version. 
However I will include it soon.

Best regards
Iñaki

**Comment by izabala123** [comment]
Hi all

QTF load from demo is now supported from https://github.com/BEMRosetta/BEMRosetta/releases/tag/June_2023_25
Please try it.

Iñaki
