### ISSUE TITLE
How to convert WAMIT format to DeepLines HDB format ?

### ISSUE THREAD

**Issue by AlexandreMssn** [BEMRosetta/BEMRosetta#23]
Hello ! 

I've just discovered BEMRosetta and it is really useful to quickly display HDB and convert from a format to another. 

Unfortunately, I am used to compute HDB using WAMIT (.1, .3, .4 ...)  and I would be interesting into converting it in the DeepLines type (.hdb) to be able to run a floating offshore wind mooring study. 

I know it is not a conversion available into BEMRosetta but I was wondering if you can provide the code for the conversion DLW to WAMIT ? It could help me create the reverse one. 

Thanks a lot
Alex

**Comment by izabala123** [comment]
Dear Alex

Currently BEMRosetta can read .hdb files and save them in .1... format and others, but cannot save as .hdb. This is apparently not a normal workflow, since with DeepLines, Principia distributes Diodore, which is an excellent radiation-diffraction solver. And in your case I would trust Diodore. 
If for whatever reason this is not possible, let me know in detail what features you require from the .hdb and we'll check it out. I would need your help, as I currently don't have DeepLines available to check that the conversion to .hdb format is correct.

Best regards
Iñaki

**Comment by AlexandreMssn** [comment]
Dear Iñaki, 

Thanks for the quick answer! 

I agree that this is not the normal workflow. But in my specific case, I currently only have a DeepLines licence and no access to Diodore. That is why I am trying to figure it out how I can convert a WAMIT type into DeepLines wind type.  

Moreover, most of the floating offshore wind open source data available (from NREL for instance) use the WAMIT type. So I was thinking that it could be interesting to be able to convert it into .hdb to run simulation on DeepLines and doing some sensitivity analysis between software for instance. 

On my side I would like to be able to generate a .hdb with : 
- "excitation forces and moments" (corresponding to .2 or .3 in WAMIT) 
- "RAO" (corresponding to .4)
- "Added mass and damping coefficient" (corresponding to .1)
- "Drift forces and moments" (corresponding to .8 or .9)
- "Hydrostatic" (correspondig to .hst)

And of course I can check with DeepLines if the format is correct.  

Thank you again :) 

Best regards
Alex

**Comment by izabala123** [comment]
Hi Alex

If you are still interested in this topic, please send me some sample files from Diodore and I will prepare the software.

Iñaki

**Comment by AlexandreMssn** [comment]
Hi Iñaki

I am still interested indeed ! I will send you some samples of Diodore files by mail. Don't hesitate if you have any question. 

Thanks :) 

Alex

**Comment by AlexandreMssn** [comment]
Hi Inaki,

Here are the samples.

Thanks again

Alex

**Comment by izabala123** [comment]
Hi Alexandre

I have got the files.
Does BEMRosetta reads properly all the data you need, including forece/rao phases?
I see data until mean drift probably with the far field method.

Iñaki

**Comment by izabala123** [comment]
Hi Alex

HDB files saving is just implemented.
Please try it.

Some comments:
- QTF load/save is not implemented (I don't have a sample file)
- HDB files have a big [INTER_RAO] section, with a higher number of periods between the range, but I don't know what it is.

Best regards
Iñaki

**Comment by AlexandreMssn** [comment]
Hi Iñaki,

I am just coming back from summer holydays.
I've quickly tried your implementation on one sample and it seems to work very well ! Thanks a lot.

I will perform more checks in the coming weeks and get back to you soon with my full feedback.

Once again thank you for this implementation

Best regards
Alex

**Comment by AlexandreMssn** [comment]
Hi Iñaki,

When importing both files (.out and the .hdb (saved from the .out)) there are some differences on two components: 

- On RAO magnitude : there is a factor 10^4 between the two files (i guess this factor is missing in the implemented hdb saving option) 
- On excitation force phase (heave and yaw) there are some inversion of the sign between the two files

I am pursuing my checks

Thx
Best regards
Alex

**Comment by izabala123** [comment]
Hi Alex

BEMRosetta considers that the RAO and force handling in .hdb is identical, the values of them in the hdb are the magnitude in dimensional value and  the phase in radians, It doesn't consider any scaling in value, and the phase follows Wamit standard.

Please describe the steps you follow and the results. Sample files would be great.

Thank you
Iñaki
