### ISSUE TITLE
Long clonging time

### ISSUE THREAD

**Issue by klugier** [BEMRosetta/BEMRosetta#27]
It seems that you are storing executable files in the repository bin directory. It contributes to significant size of the repository. For example when you cloning BEMRosetta repository it weights 1.3 GB.

As an alternative you can consider using "Releases"  (https://github.com/BEMRosetta/BEMRosetta/releases) or "Packages" (https://github.com/orgs/BEMRosetta/packages?repo_name=BEMRosetta).

![BEMRosettaClone](https://github.com/BEMRosetta/BEMRosetta/assets/6963025/3264a48e-ddc4-4f2e-99c9-fca2872892fc)

**Comment by izabala123** [comment]
Hi Zbigniew

Good idea. I have removed the bin folder and added the binaries in Releases.

Best regards
Iñaki

**Comment by klugier** [comment]
Hello @izabala123 ,

It partially solves the problem, because while cloning the repository git needs to take into account the history of the repo. It means that all historical binary releases needs to be downloaded.

The good think is that you repo will not grow in the near future, due to movement of release to separate place. To compress the size of the repository you will need to delete repository history. The process is described on this [page](https://medium.com/@sangeethkumar.tvm.kpm/cleaning-up-a-git-repo-for-reducing-the-repository-size-d11fa496ba48). If you decided to do it, please be very careful. The operation will not be withdrawn.

Fast cloning time is desired by the repository users, especially when they are cloning your repository for the first time. 1,3 GB is definitely too match, if you limit your repository size to less than 100 Mb then initial experience will be much more better.

Klugier

**Comment by izabala123** [comment]
Hi Zbigniew

I have done my best spending many hours trying to reduce repository size, by removing selected files with git filter-repo and BFG, and after some tries, to remove all history, but unsuccessfully.

Best regards
Iñaki
