### ISSUE TITLE
Infinite frequency addedd mass

### ISSUE THREAD

**Issue by hachikoi1** [BEMRosetta/BEMRosetta#28]
Dear [izabala123](https:github.com/izabala123)
    I found AQWA calculates the infinite frequency added mass as ADDEDMASS_HF (100.0RAD/S), which is different from that of BEMRosetta. Does BEMRosetta calculate the infinite frequency added mass based on radiation IRF as $R_{ij}(t)=\frac{2}{\pi}\int_{0}^{\infty}B(\omega)\cos(\omega t)d\omega$ and $A_{ij}(\infty)=A_{ij}(\omega)+\frac{1}{\omega}\int_{0}^{\infty}R_{ij}(t)\sin(\omega t)dt$?

The infinite frequency added mass calculated by BEMRosetta seems to be more accurate than that by WEC-Sim, especially in yaw direction. What optimization has BEMRosetta done in the calculation? Consider more frequency component?

![image](https://github.com/BEMRosetta/BEMRosetta/assets/106663159/530ddcd5-9c39-4edd-88f9-14540bf349ff)

Looking forward to your reply

Best regards,

Tianyuan

**Comment by izabala123** [comment]
Hi Tianyuan

Yes, if AQWA includes the A(100 rad/s), BEMRosetta reads it as the Ainf. In the same way, if there is a A(0.001 rad/s), it considers it is A0. 
However, if in Options, this is checked:
![image](https://github.com/BEMRosetta/BEMRosetta/assets/38589221/0f27e3e9-bd82-4efe-870a-391b016f9e5a)

or you tap on Process/Ainf
![image](https://github.com/BEMRosetta/BEMRosetta/assets/38589221/6540203d-99dc-4295-82b1-2fef34ec6515)

BEMRosetta calculates Ainf using the normal equations you have included. It doesn't use any 'magic sauce', it just applies the equations. Remember that some details affect the quality, as to get the IRF you need to set the last to terms:
![image](https://github.com/BEMRosetta/BEMRosetta/assets/38589221/2f54e299-e06d-4fa5-b72c-0904a4aa4517)

If you set a 'max time' value too high, BEMRosetta tries to convince you to set a probably wiser one.

Best regards
Iñaki

**Comment by hachikoi1** [comment]
Dear [izabala123](https://github.com/BEMRosetta/BEMRosetta/issues/github.com/izabala123)

Many thanks for your work. 

I previously discussed the AQWA phase angle with Kumars Mahmoodit and he mentioned that he had discussed it with you.
 
- Wamit: force = polar(ma, ph*pi/180)
- OrcaWave : force = polar(ma, ph*pi/180)
- AQWA: force = polar(ma, -ph*pi/180)
- Nemoh: force = polar(ma, -ph)
- Diodore : force = polar(ma, ph)

I also found AQWA outputs the local parameter phase angle, but not the sum (wave and parameter) phase angle. The latter is a global phase angle, as WAMIT outputs. 

For a single body with an offset of its COG from the global coordinate origin or multibody cases, does BEMRosetta consider the wave phase angle due to the location offset of COG from global coordinate origin.

Best regards,

Tianyuan Wang

**Comment by izabala123** [comment]
Dear Tianyuan 

Now BEMRosetta just loads the phase as it is in the original files. 
If everything, the body, and the cog, it is in 0,0,0, no difference should arise. However, in other situations the phase may change.
For it, **I would like to contact with somebody with Wamit to do some very simple tests**, and compare them with other solvers. This way, BEMRosetta would filter the solver internal criterion and show the results of different solvers with the same criterion. 
For now I haven't found anybody with Wamit :anguished:

Best regards
Iñaki

**Comment by izabala123** [comment]
Well, this

> Now BEMRosetta just loads the phase as it is in the original files.

 is really wrong: BEMRosetta really tries to follow Wamit phase criterion. It considers this:

>     Wamit: force = polar(ma, ph*pi/180)
>     OrcaWave : force = polar(ma, ph*pi/180)
>     AQWA: force = polar(ma, -ph*pi/180)
>     Nemoh: force = polar(ma, -ph)
>     Diodore : force = polar(ma, ph)

Iñaki
