### ISSUE TITLE
Morison elements

### ISSUE THREAD

**Issue by yizhezhang1** [BEMRosetta/BEMRosetta#29]
Dear @izabala123 
 I tried to read mesh from AQWA with BEMRosetta,but i found that the BEMRosetta can not read the morison elements which i have already set in AQWA ,i do not know how to read morison elements with  BEMRosetta.

Best regard!
zz

**Comment by izabala123** [comment]
Oh, I am sorry Yizhe Zhang

Now BEMRosetta cannot read Morison elements. On this issue, not all solvers treat these elements in the same way. That is why I have not included it yet. 
If you want, so that you can get started, I can give you instructions on how to interpret them.

Iñaki

**Comment by yizhezhang1** [comment]
Dear @izabala123 
Thanks a lot! I really want to know that how to interpret the morison elements. 
 BEST REGARD!

**Comment by izabala123** [comment]
Hi Yizhe Zhang. I hope to give you soon the explanation.

**Comment by izabala123** [comment]
Hi Yizhe Zhang

AQWA is a complex software. However I will try to give you some explanations.

The DAT files are divided in 'DECK'. The '*' in the beginning of a row is to comment out that row.

DECK 1 includes the nodes, or important points, as XYZ. Nodes that define Morison elements are defined with ids from 100000, like 195100, where the first '1' indicates the body id. Please try not to repeat node ids.

Morison elements that I know are TUBE and DISC. TUBE are the normal tubes , and DISC are like heave plates, with negligible length.

Morison elements are defined in DECK 2. You can find them like this:
`     1DISC       108(1)(95100)(95101)(95100)`
`     1TUBE      108(1)(95100)(95101)(95100)(95101)`
Where 1 is the body id, DISC is the type of element, and the last numbers are the nodes that define the Morison element. These have removed the id of the element, so id 195101 appears there as (95101) of body 1.

- DISC is defined by the node of the position, a node marking the direction, and a node marking the properties (drag, ...)

- TUBE is defined by the node of the beginning, a node marking the end, a node marking the properties (drag, ...) of the beginning and a node marking the properties of the end.

Nodes properties are in DECK 4. 
You set them in two lines. Here two examples
```
     1DISC     95100    4.1                 
     1CONT              8.2    0.0001

     1TUBE     95188    2.5E-2     1.8E-2     0
     1CONT              513    1.34E-3
```

- For DISC, you set diameter, drag, added mass
- For TUBE, you set diameter, thickness, sealed (0 sealed, 1 open), drag, added mass

I hope you find these tips useful.

Best regards
Iñaki
