### ISSUE TITLE
How to output the hydrostatic result .hst (WAMIT) from the multi-body results of Nemoh?

### ISSUE THREAD

**Issue by getChaos22** [BEMRosetta/BEMRosetta#30]
Hello, [izabala123](https://github.com/BEMRosetta/BEMRosetta/issues/github.com/izabala123)!

Is it possible to output the .hst file from the multi-body results of Nemoh? It seems like Nemoh cannot calculate the static problem of multi-body, because one can only specify one mesh.cal in the case directory. But I noticed that in the BEMRosetta-BEMSolver, it is possible to save multiple mesh.cal files, such as mesh_0.cal, mesh_1.cal, mesh_2.cal...

So, I was wondering is there a way to output a static file .hst for the multi-body of Nemoh, even if the coupling between the free degrees of different bodies are not considered?  

BTW, even though BEMRosetta can give multiple mesh.cal files, but it looks like the Nemoh's hydrosCal.exe cannot use them. Do you have any ideas?

Thanks so much

Chao Li

**Comment by izabala123** [comment]
Hello Chao Li

In BEMRosetta I have done my best to include Nemoh's multi-body treatment, but as you have seen, there is no clear way to do it. I advise you to  either body to body with Nemoh, or with BEMRosetta itself. You can open the mesh, include the mass, COG, centre of reference, and you get the stiffness matrix that you can save as .hst.

Best regards
Iñaki

**Comment by getChaos22** [comment]
Hi Iñaki
Thanks for your reply. 
For the method done by BEMRosetta, do you mean to save the stiffness matrix as .hst for the multiple bodies one by one  (as shown in the picture), and then assemble these .hst files to be a complete one? 
![image](https://github.com/BEMRosetta/BEMRosetta/assets/120010727/27809691-6a8f-471b-965b-0833c03f8c43)
Another question is, I know how to input the COG, but where I can set the center of reference? Is it in the C. Motion?
Thanks again.

Best regards
Chao Li

**Comment by getChaos22** [comment]
Hi Iñaki

Another question is that, BEMRosetta seems like cannot output the coupling radiation coefficients (added mass and damping) of different bodies of Nemoh to the WAMIT .1 file. The following two screenshots are the Nemoh's RadiationCoefficients.tec and the corresponding WAMIT 's .1 file generated by BEMRosetta. In this case two floating bodies are considered. Obviously, Nemoh gives the coupling term of different bodies, but these terms are zero in .1 file.

Sceenshot of Nemoh's RadiationCoefficient.tec
![image](https://github.com/BEMRosetta/BEMRosetta/assets/120010727/5d23b35f-2e2e-4c37-84e1-68368cc03c2b)

Sceenshot of WAMIT's .1 file
![image](https://github.com/BEMRosetta/BEMRosetta/assets/120010727/9706cf74-25dc-4e0b-b467-2b37bc4f6224)

Further, the curve of added mass and damping drawn by BEMRosetta also cannot reflect the coupling effect of different bodies.
![image](https://github.com/BEMRosetta/BEMRosetta/assets/120010727/3341ca12-6c59-43f7-b67f-e020f1d55040)

Do you have any idea about these question?

Thanks so much.

Best regards
Chao Li

**Comment by izabala123** [comment]
> Hi Iñaki Thanks for your reply. For the method done by BEMRosetta, do you mean to save the stiffness matrix as .hst for the multiple bodies one by one (as shown in the picture), and then assemble these .hst files to be a complete one? ![image](https://user-images.githubusercontent.com/120010727/252850050-27809691-6a8f-471b-965b-0833c03f8c43.png) Another question is, I know how to input the COG, but where I can set the center of reference? Is it in the C. Motion? Thanks again.
> 
> Best regards Chao Li

Dear Chao Li

Yes, c. motion is the centre of the reference system. About the .hst, I understood that you needed as many .hst as bodies. If you need one .hst for all the bodies, simply select them all and click on Join, then get the .hst. If you have any problem please tell me.

Best regards
Iñaki

**Comment by izabala123** [comment]
> Hi Iñaki
> 
> Another question is that, BEMRosetta seems like cannot output the coupling radiation coefficients (added mass and damping) of different bodies of Nemoh to the WAMIT .1 file. The following two screenshots are the Nemoh's RadiationCoefficients.tec and the corresponding WAMIT 's .1 file generated by BEMRosetta. In this case two floating bodies are considered. Obviously, Nemoh gives the coupling term of different bodies, but these terms are zero in .1 file.
> 
> Sceenshot of Nemoh's RadiationCoefficient.tec ![image](https://user-images.githubusercontent.com/120010727/253195188-5d23b35f-2e2e-4c37-84e1-68368cc03c2b.png)
> 
> Sceenshot of WAMIT's .1 file ![image](https://user-images.githubusercontent.com/120010727/253196833-9706cf74-25dc-4e0b-b467-2b37bc4f6224.png)
> 
> Further, the curves of added mass and damping drawn by BEMRosetta also cannot reflect the coupling effecst of different bodies. ![image](https://user-images.githubusercontent.com/120010727/253198875-3341ca12-6c59-43f7-b67f-e020f1d55040.png)
> 
> Do you have any idea about these questions?
> 
> Thanks so much.
> 
> Best regards Chao Li

Dear Chao Li

Thank you for your feedback. I will check it out and get back to you soon.

Best regards
Iñaki

**Comment by izabala123** [comment]
> > Hi Iñaki
> > Another question is that, BEMRosetta seems like cannot output the coupling radiation coefficients (added mass and damping) of different bodies of Nemoh to the WAMIT .1 file. The following two screenshots are the Nemoh's RadiationCoefficients.tec and the corresponding WAMIT 's .1 file generated by BEMRosetta. In this case two floating bodies are considered. Obviously, Nemoh gives the coupling term of different bodies, but these terms are zero in .1 file.
> > Sceenshot of Nemoh's RadiationCoefficient.tec ![image](https://user-images.githubusercontent.com/120010727/253195188-5d23b35f-2e2e-4c37-84e1-68368cc03c2b.png)
> > Sceenshot of WAMIT's .1 file ![image](https://user-images.githubusercontent.com/120010727/253196833-9706cf74-25dc-4e0b-b467-2b37bc4f6224.png)
> > Further, the curves of added mass and damping drawn by BEMRosetta also cannot reflect the coupling effecst of different bodies. ![image](https://user-images.githubusercontent.com/120010727/253198875-3341ca12-6c59-43f7-b67f-e020f1d55040.png)
> > Do you have any idea about these questions?
> > Thanks so much.
> > Best regards Chao Li
> 
> Dear Chao Li
> 
> Thank you for your feedback. I will check it out and get back to you soon.
> 
> Best regards Iñaki

Dear Chao Li

Looking at your message, I see that you are referring to the 2_2Bodies case which is among the TestCases included in Nemoh. I attach a more complete screenshot of RadiationCoefficients.tec.

![image](https://github.com/BEMRosetta/BEMRosetta/assets/38589221/9a9d81e5-38f0-4c3f-ab68-05416b5eaaa1)

You can see in the yellow circle that there are no 1-7, to 1-12 terms, just 1-1 to 1-6, and 2-1 to 2-6, so there are no crossed terms. If you read the data included, that makes sense, as there are 1 + 6x2 + 6x2 = 25 columns.

Please confirm if this is the case. If not, let me know and we will check it.

Best regards
Iñaki

**Comment by getChaos22** [comment]
> > > Hi Iñaki
> > > Another question is that, BEMRosetta seems like cannot output the coupling radiation coefficients (added mass and damping) of different bodies of Nemoh to the WAMIT .1 file. The following two screenshots are the Nemoh's RadiationCoefficients.tec and the corresponding WAMIT 's .1 file generated by BEMRosetta. In this case two floating bodies are considered. Obviously, Nemoh gives the coupling term of different bodies, but these terms are zero in .1 file.
> > > Sceenshot of Nemoh's RadiationCoefficient.tec ![image](https://user-images.githubusercontent.com/120010727/253195188-5d23b35f-2e2e-4c37-84e1-68368cc03c2b.png)
> > > Sceenshot of WAMIT's .1 file ![image](https://user-images.githubusercontent.com/120010727/253196833-9706cf74-25dc-4e0b-b467-2b37bc4f6224.png)
> > > Further, the curves of added mass and damping drawn by BEMRosetta also cannot reflect the coupling effecst of different bodies. ![image](https://user-images.githubusercontent.com/120010727/253198875-3341ca12-6c59-43f7-b67f-e020f1d55040.png)
> > > Do you have any idea about these questions?
> > > Thanks so much.
> > > Best regards Chao Li
> > 
> > 
> > Dear Chao Li
> > Thank you for your feedback. I will check it out and get back to you soon.
> > Best regards Iñaki
> 
> Dear Chao Li
> 
> Looking at your message, I see that you are referring to the 2_2Bodies case which is among the TestCases included in Nemoh. I attach a more complete screenshot of RadiationCoefficients.tec.
> 
> ![image](https://user-images.githubusercontent.com/38589221/254720732-9a9d81e5-38f0-4c3f-ab68-05416b5eaaa1.png)
> 
> You can see in the yellow circle that there are no 1-7, to 1-12 terms, just 1-1 to 1-6, and 2-1 to 2-6, so there are no crossed terms. If you read the data included, that makes sense, as there are 1 + 6x2 + 6x2 = 25 columns.
> 
> Please confirm if this is the case. If not, let me know and we will check it.
> 
> Best regards Iñaki

Dear Iñaki

Thanks for your reply, but I don't think the coupling effects (or cross terms) of different bodies are excluded in  RadiationCoefficients.tec, here are my opinions.

For the information in the yellow circle, I think the second column and the fifth column are body Nos but not DoFs (Please see Screenshot 1). So the information just shows how many DoFs are included for each body. It doesn't contain the coupling information of the multi-body. If some DoFs of a body are closed in Nemoh.cal (i.e. the fourth DoF of Body 1), the total number of DoFs of the body shown here will be reduced (Please see Screenshot 1) . 
![image](https://github.com/BEMRosetta/BEMRosetta/assets/120010727/74ce438c-2a70-424a-a16c-8c2184db30f4)

The following data in RadiationCoefficients.tec is divided by DoFs of each body (please see Screenshot 2), which are given in the head of the file. In the formula 1 + 6x2 + 6x2 = 25 columns, did you mean the first 6x2 is the 6 DoFs of the body 1 and the second 6x2 is the 6 DoFs of the body 2 (uncoupled with the body 1)? If so, how to explain the information shown in the DoFs of body 2 (please see Sreenshot3)? Meanwhile, it also makes sense if we regard the 25 columns as 1 + 1x12x2, i.e. the 12 DoFs coupled with the present DoF.
![image](https://github.com/BEMRosetta/BEMRosetta/assets/120010727/4a3cf9ea-7412-426e-9543-be871509da65)

![image](https://github.com/BEMRosetta/BEMRosetta/assets/120010727/f14403e5-eeaa-4410-9a09-a332c9fb48be)
 
Therefore, I think the cross terms of different bodies are considered in RadiationCoefficients.tec.

I'm not sure if my expression is clear, just let me know if there are any questions.

Thanks again!

Best regards
Chao Li

**Comment by getChaos22** [comment]
> > Hi Iñaki Thanks for your reply. For the method done by BEMRosetta, do you mean to save the stiffness matrix as .hst for the multiple bodies one by one (as shown in the picture), and then assemble these .hst files to be a complete one? ![image](https://user-images.githubusercontent.com/120010727/252850050-27809691-6a8f-471b-965b-0833c03f8c43.png) Another question is, I know how to input the COG, but where I can set the center of reference? Is it in the C. Motion? Thanks again.
> > Best regards Chao Li
> 
> Dear Chao Li
> 
> Yes, c. motion is the centre of the reference system. About the .hst, I understood that you needed as many .hst as bodies. If you need one .hst for all the bodies, simply select them all and click on Join, then get the .hst. If you have any problem please tell me.
> 
> Best regards Iñaki

Got it.
Thanks for your reply!
Best regards
Chao Li
