### ISSUE TITLE
Aqwa to WAMIT output for Openfast error !

### ISSUE THREAD

**Issue by rahulcr33** [BEMRosetta/BEMRosetta#31]
Hello Iñaki,

I was trying to export results from Aqwa to wamit output files for using with openfast. I encountered the following error while running openfast. Have you even come across this error? Do you know how to solve this? Is it possible to solve this error using the newly added processing features of BEMRosetta ?

![340ef669229ec981e5ea1d5086f315ccab0997d2](https://github.com/BEMRosetta/BEMRosetta/assets/86499230/27ac51e2-e66c-4d02-8313-4a8b47868ceb)

Regards,

Rahul.

**Comment by izabala123** [comment]
Hi Rahul

The error you mention rings a bell, but I don't remember it. I guess you have already looked at the NREL forum. If you can't get QTF with more frequencies, you can try with BEMRosetta to fill with interpolated values a higher number of frequencies, with the option that I indicate in the screenshot.

![image](https://github.com/BEMRosetta/BEMRosetta/assets/38589221/9028ac23-25dc-4184-9cca-b3275d5da7ef)

Best regards
Iñaki

**Comment by rahulcr33** [comment]
Hi Iñaki,

I tried this feature and it is working. Openfast has some issues with wave directions for the QTFs, I think. The link to the NREL Forum is not working on this pop up.

Thank you,

Rahul.

![Screenshot 2023-07-12 110220](https://github.com/BEMRosetta/BEMRosetta/assets/86499230/e5d3347a-5d33-4e30-bb68-1b59fc20e87b)

**Comment by izabala123** [comment]
Thank you Rahul

I have removed the link to the Forum. I will upload the change soon.

Best regards
Iñaki

**Comment by rahulcr33** [comment]
Hi Iñaki,

I may have found another issue. The RAOs calculated by Aqwa and read by BEMRosetta appears to be different. I read the .LIS file of a simulation in aqwa and this is the result from BEMRosetta.

![image](https://github.com/BEMRosetta/BEMRosetta/assets/86499230/fa3e8794-3b1d-46e5-b2e0-89d6e9ef3bd6)

The RAOs from aqwa is this:

![image](https://github.com/BEMRosetta/BEMRosetta/assets/86499230/2e66a65f-33d5-4334-960c-74971b26892a)

They are not matching. MaybeI did something wrong?

Regards,

Rahul.

**Comment by izabala123** [comment]
Hi Rahul

Please try the last version, and show me too the RAO for heave.
Thank you.

Iñaki

**Comment by rahulcr33** [comment]
Hi Iñaki,

It appears to be working properly now.

Thank you,
Rahul.

![image](https://github.com/BEMRosetta/BEMRosetta/assets/86499230/68762586-2114-46a1-80d6-eb81a938c1c0)

![image](https://github.com/BEMRosetta/BEMRosetta/assets/86499230/d8bf9952-370d-4a41-94ce-1df23e2a15e1)

**Comment by izabala123** [comment]
Excellent!. Thank you.
