### ISSUE TITLE
Load the Multi-body hydrodynamic coefficient(.out file) from hydrostar

### ISSUE THREAD

**Issue by YangLeiTH** [BEMRosetta/BEMRosetta#36]
Hi @izabala123 

When loading the Multi-body hydrodynamic coefficient(.out file) from Hydrostar, it reported a bug as follows.
![image](https://github.com/BEMRosetta/BEMRosetta/assets/119639841/e044cf89-1a16-4f0f-89dc-93810d413562)
It seems that the BEMRosetta can only load the single-body coefficient(.out file) from Hydrostar? The file exported from Hydrostar is attached.

Best regards,
[oc4.zip](https://github.com/BEMRosetta/BEMRosetta/files/13303141/oc4.zip)

**Comment by izabala123** [comment]
Hi Yang

Thank you for your post and your enclosed file. HydroStar has some particularities on the out format, and a multy body case as yours have some more. I have adapted the source and I hope it works well for you now.

Best regards
Iñaki

**Comment by YangLeiTH** [comment]
Thank you! It ran successfully

**Comment by izabala123** [comment]
Excellent. Thank you.

**Comment by izabala123** [comment]
Dear Yang

I have a simple question about HydroStar that I wanted to ask you. Please confirm if you are available. 
Thank you!

Best regards
Iñaki

**Comment by izabala123** [comment]
Dear @YangLeiTH 

A new version is uploaded with improvements for HydroStar .out.
Now the .mcn file is read if available to avoid misunderstandings regarding the global and body axis.

Best regards
Iñaki
