### ISSUE TITLE
Bladed support

### ISSUE THREAD

**Issue by izabala123** [BEMRosetta/BEMRosetta#4]
Dear Iñaki,

Yes, you helped me a lot! These are the files the program Bladed is asking for. The .cfg file is only needed for the IALTFRC value so that would be easy. Also, the .frc is easy to make by putting the mass/inertia matrix in correct format. The .out file is a bit more tricky. 

![image](https://user-images.githubusercontent.com/52451695/80680310-cdd61480-8abe-11ea-8d03-a1d6d4614a1a.png)

Kind regards, 

Martijn

_Originally posted by @martijnwilpshaar in https://github.com/izabala123/BEMRosetta/issues/3#issuecomment-621648332_

**Comment by izabala123** [comment]
Dear Martijn

I have created this new issue with your last post.
If you could send me a sample of each of these files, with this explanation, I can prepare a filter to create them from Nemoh or AQWA data. Fortunately as BEMRosetta reads .out files, the format is known. However, reading the enclosed Bladed file descriptions, there may be some tricks, as normal .out files enclose .1 and .3 data.

Best regards
Iñaki

**Comment by martijnwilpshaar** [comment]
Hi Iñaki,

Sorry for my late reply, I was busy with some other things. 
Anyways: I did try to manually make these files and succeeded with doing that using the structure of the files indicated in the Wamit 6.4 manual information. I attached the sample files for the .pot, .cfg, .frc files. 
[sampleFRC.txt](https://github.com/izabala123/BEMRosetta/files/4592358/sampleFRC.txt)
[samplePOT.txt](https://github.com/izabala123/BEMRosetta/files/4592359/samplePOT.txt)
[sampleCFG.TXT](https://github.com/izabala123/BEMRosetta/files/4592360/sampleCFG.TXT)

IF in the .cfg file IALTFRC=1 --> .frc expects no density (3rd line skipped), only a VCG (4th line only one value), radii of gyration (3x3) matrix instead of the mass-inertia (6x6) matrix.
IF in the .cfg file IALTFRC=2 --> .frc expects density (3rd line as in example), CoG (4th line as in example), mass-inertia (6x6) matrix (as in example).

**Comment by izabala123** [comment]
Thank you Martijn

I think that with your indications, basic .frc, .pot and .cfg files can be created.
It would be great if you could help me to validate in Bladed .out files from BEMRosetta.
Could you send me a set of files from Nemoh or Wamit, to be converted with BEMRosetta to .out, .frc, .pot and .cfg formats, for you to test them later in Bladed?
If the answer is positive, I will implement it all.

Best regards
Iñaki

**Comment by martijnwilpshaar** [comment]
Dear Iñaki,

I would be happy to help you by checking the outputs in Bladed. This will also save me time in the future. 

Here are two simple examples of finished Nemoh simulations I did (one simple buoy in 3DOF) and two interacting buoys. I cannot share any complete floating wind turbine platform unfortunately but if the conversion works on these buoys I would expect it also work on different platforms. Let me know when you want me to check in Bladed. The hardest part is I think the .FRC file containing the mass-inertia matrix. This is not calculated by Nemoh. You can however try estimating this from the submerged shape and submerged volume. 

[buoy_onebody_3dof.zip](https://github.com/izabala123/BEMRosetta/files/4634683/buoy_onebody_3dof.zip)
[buoy_twobody_3dof.zip](https://github.com/izabala123/BEMRosetta/files/4634684/buoy_twobody_3dof.zip)

**Comment by izabala123** [comment]
Thank you Martijn

With your support and availability to test the results in Bladed, I will begin with the task.

However , if .FRC includes the inertia terms for the floating body, I do not think it can be obtained from submerged shape and volume. All dynamic terms about floating body, lets say, mass, cg, inertia matrix, external shape, depend on itself. In real devices, they can be obtained from tests (inclination, moving weights in the vessel, etc, or in case of small size models, hanging them with a wire, etc), but this is not applicable here.

Best regards
Iñaki

**Comment by martijnwilpshaar** [comment]
Dear Iñaki,

The way I understand is that you can have two possibilities for the .FRC file. One option is to include the inertia-mass matrix, which needs these tests. Second option is to include the radius of gyration. This radii of gyration matrix should be possible to estimate: 

"assuming that “the mass of the body is equal to its displacement and that the mass is
distributed on the surface of the body.” At least, this is the way it is calculated using WAMIT.

Right?

Kind regards,

Martijn

**Comment by izabala123** [comment]
Dear Martijn

The point is that the dynamics of a volume of water is not the same as that of a steel structure.
However, for a first approximation, we could include the inertial matrix of a volume of water.

Best regards
Iñaki

**Comment by martijnwilpshaar** [comment]
Dear Iñaki, 

I was wondering if you already found some time to look into making these improvements on BEMRosetta. 

Kind regards,

Martijn

**Comment by izabala123** [comment]
Sorry Martijn. So far I haven't had time.

**Comment by martijnwilpshaar** [comment]
Dear Iñaki,

Ah, alright. Let me know when you made some progress regarding this topic. 

Kind regards,

Martijn

**Comment by izabala123** [comment]
Hello Martijn

First version of Wamit .out output has been added. If it works for you, the rest of changes will be very easy.

Best regards
Iñaki

**Comment by izabala123** [comment]
It has been a few months since the implementation of this feature, so I think this issue can be closed.
