### ISSUE TITLE
Only opens master on Windows computer 

### ISSUE THREAD

**Issue by donajose1211** [BEMRosetta/BEMRosetta#40]
After download, following the instructions, it only opens as the master on U++ on my windows computer. Is there a way to get it to open the display file?

**Comment by izabala123** [comment]
Sorry donajose, I don't understand you well.

I don't understand the meaning of "opens as the master on U++", or "to open the display file".

Best regards
Iñaki

**Comment by donajose1211** [comment]
Sorry, I have attached an example of what opens up. I was wondering how I can get from this to the main mesh handling bit?
[image0.jpeg]

On 7 Mar 2024, at 20:14, Iñaki Zabala ***@***.***> wrote:

﻿

Sorry donajose, I don't understand you well.

I don't understand the meaning of "opens as the master on U++", or "to open the display file".

Best regards
Iñaki

**Comment by izabala123** [comment]
Hi donajose,

As far as I can see, you have everything almost ready!
You have installed U++ correctly, you have opened the U++ IDE (TheIDE) and from UppHub you have downloaded BEMRosetta and all the necessary libraries. Now you just have to compile and run BEMRosetta. In TheIDE, to do this, just press F5. If you have any more problems, we can meet up for a moment.

Iñaki

**Comment by izabala123** [comment]
Hi donajose,

I get the feeling that the version of U++ you are using is not the latest.
Can you confirm that you are using an updated version of U++?

Iñaki

**Comment by donajose1211** [comment]
Hi Iñaki, 
That’s worked! Thank you so much!

**Comment by izabala123** [comment]
Excellent. I am very pleased.
