### ISSUE TITLE
Issue when importing External Damping matrix and External stiffness matrix from Wamit to Rosetta.

### ISSUE THREAD

**Issue by Cesar-dotcom** [BEMRosetta/BEMRosetta#44]
Hi @izabala123 

I have noticed that the import process for the External Dimensional Damping Matrix (EXDAMP) and the External Dimensional Stiffness Matrix (EXSTIF) in Rosetta is wrong.
In the pictures below you can see the two matrices. In this case, what I expect to be the Additional Linear Damping Matrix is placed in the Mooring Stiffness Matrix and vice versa.
![rosettaBug1](https://github.com/BEMRosetta/BEMRosetta/assets/76446423/aced9119-fe12-499b-841c-a2cac10a1a81)
![rosettaBug](https://github.com/BEMRosetta/BEMRosetta/assets/76446423/22e48e3f-6396-43b0-91cb-f4b4f02a6b17)

I am also attaching a screenshot of the Force file from Wamit.
![rosettaBug2](https://github.com/BEMRosetta/BEMRosetta/assets/76446423/a2817d63-90c5-4fab-bd9e-6b40b2100e0f)

Thank you in advance for all the great work on this software!

**Comment by Cesar-dotcom** [comment]
Hi Iñaki,

You are right, when uploading the .frc file in BEMRosetta, it only reads the EXDAMP matrix and does it correctly. However, I have to do it in a separate folder, not in the project folder. 
If I do this in the project folder, when uploading the .frc file, the same happens in the screenshots I attached in the issue at the beginning. It seems it uploads information from the whole project folder because it also loads Added Mass and Damping, load RAO's and motion RAO's.

Best regards
Cesar

**Comment by izabala123** [comment]
Hi Cesar

Yes, that's it. Wamit spreads the info in different files so, depending on the file you give BEMRosetta, it does different things:
- .out: This includes all. BEMRosetta doesn't care of other files.
- Any other file: BEMRosetta reads all available files in that folder trying to pick up all the data.

If you have any problem please send a sample file or set of them and I will solve it immediately.

Best regards
Iñaki

**Comment by Cesar-dotcom** [comment]
Hi Iñaki,

I'm sorry for not getting back to you sooner. I can't share any of these files due to NDA, but thanks for explaining how BEMRosetta works.

Best regards
César

**Comment by izabala123** [comment]
You are welcome. Happy solving.
