### ISSUE TITLE
Some questions about the added mass and radiation damping coefficients

### ISSUE THREAD

**Issue by Laveran96** [BEMRosetta/BEMRosetta#48]
Dear @izabala123 ，

I have two questions about the added mass and radiation damping coefficients in BEMRosetta

1. When I was using BEMRosetta to read the results from AQWA, I found two curves in the graph of the added mass and radiation damping, labeled as 'Aij Analysis' and 'A potentials ij Analysis' or 'Bij Analysis' and 'B potentials ij Analysis'.  Could you tell me the difference between 'A Analysis' and 'A potentials Analysis'? Is the data of 'A potentials Analysis' calculated by BEMRosetta. What are the algorithmic differences between them?
2. In Hydro Coeff→mesh&potentials, details of the mesh elements are provided, such as A_surge_surge, B_pitch_surge.  Does the data represent the added mass and radiation damping of the panels? How is this data calculated? I would like to understand the detailed algorithm behind it. Could you please provide some information? 

Best regards

**Comment by izabala123** [comment]
Hi @Laveran96 

As you know, the hydrodynamic coefficients are obtained from a potential flow analysis. The potentials treated are the radiation, diffraction and incident potentials. The radiation potential gives the added mass and the radiation damping, the diffraction potential gives the diffraction force, and the incident potential gives the Froude-Krylov force. Each of these three problems is solved for each panel of the mesh, i.e. for each panel we have the radiation, diffraction and incident potentials. With a simple operation, the pressure in each panel is obtained from the potential. And with another simple operation, the force is obtained for each panel, and is applied at the centre of the body's reference system.

To give more detailed information, now BEMRosetta handles the information by panel mesh, it the potential flow calculation provides it. Now the three problems are handled from Capytaine and OrcaWave, and the potential is handled from AQWA.

To check that the results are handled properly, choosing Apot, it will appear a new plot, obtained from the mesh potentials by BEMRosetta, that should match with the provided by the solver. Similar to this is the Bpot for radiation, Fscpot for diffraction and Ffkpot for incident. 

All this data, per panel, is listed in the Mesh&potentials tab. In these lists, every effort has been made to follow Wamit's criteria, although each solver uses its own criteria. With this information, it is possible to break down the forces by subsets of the structure, allowing structures that do not behave as rigid solids to be analysed. This makes it possible to analyse the frequencies of the structure and the stresses on internal joint elements..., if your solver is able to handle this. And now there are even open solvers that do can.

I sincerely believe that this will be a great advance over what is commonly accepted now. 

Apart from them, it is also possible to get the 1st order incident forces directly from the mesh (super fast), and to get the radiation damping from the forces using the Haskind relation.

Best regards
Iñaki

**Comment by izabala123** [comment]
Hi @Laveran96 

Considering that the radiation potential is
![image](https://github.com/user-attachments/assets/4248f108-ae64-4054-ab73-3c9a0979ac08)

the equation used by AQWA to get the added mass A and radiation damping B is this one
![image](https://github.com/user-attachments/assets/5a0dc6d4-baf9-4a32-800f-ea7295b2667c)

where nj is like this:
![image](https://github.com/user-attachments/assets/1f206b31-f732-4d7d-84ba-770aae40719c)

In BEMRosetta, you have to go to BEMRosetta_cl/Hydro2.cpp, functions A_pan() and B_pan, that do this to get the A and B per panel:
```
A = ρ Re(Φ) n ds
B = -ρω Im(Φ) n ds
```
In the same file, in function AfterLoad(), this is done to get the total A and B:

```
Value6D n;
for (int ib = 0; ib < dt.Nb; ++ib)  {
	const Value3D &c0 = dt.msh[ib].dt.c0;
	for (int ip = 0; ip < dt.pots_rad[ib].size(); ++ip) {
		dt.msh[ib].dt.mesh.panels[ip].NormalExt(n, c0);	
		for (int ifr = 0; ifr < dt.Nf; ++ifr) 
			for (int idf2 = 0; idf2 < 6; ++idf2) 
				for (int idf1 = 0; idf1 < 6; ++idf1) {
					dt.A_P[idf1 + ib*6][idf2 + ib*6][ifr] += (dt.Apan(ib, ip, idf1, idf2, ifr) = A_pan(ib, ip, idf1, idf2, ifr, n));
					dt.B_P[idf1 + ib*6][idf2 + ib*6][ifr] += B_pan(ib, ip, idf1, idf2, ifr, n);
				}
	}
}
```

If you are thinking in anything special just tell me, I may implement it. This area is in active development.

Best regards
Iñaki

**Comment by Laveran96** [comment]
Dear @izabala123 

Thank you for your prompt response. I have understood this algorithm and I found the relevant code based on your reply. It is very helpful to me. 
Thank you once again for your help and support.

Best regards
Laveran

**Comment by izabala123** [comment]
I am glad. 

Remember that the criteria for the potentials are not the same for the different solvers... but the results must be the same.

Best regards
Iñaki
