### ISSUE TITLE
Irregular frequency removal issue

### ISSUE THREAD

**Issue by cckimball** [BEMRosetta/BEMRosetta#49]
Between Feb 2024 and Aug 2024 versions lost the capability to correctly remove irregular frequencies.

In the Feb 2024 version this was working well to remove irregular frequencies on an h5 file, but the Aug 2024 version says none found for the same file.

Workflow: Hydro Coeff --> Advanced --> Irregular frequencies handling and removal --> check "Z peaks removal" and Ogilvie compliance

**Comment by izabala123** [comment]
Hi @cckimball

I think the problem is solved. Please try it.

Best regards
Iñaki

**Comment by cckimball** [comment]
Yes looks good, @izabala123! Thank you!
