### ISSUE TITLE
Error exporting h5 file

### ISSUE THREAD

**Issue by cckimball** [BEMRosetta/BEMRosetta#51]
Using most recent version: Version beta 2024081208, release, 64 bits.

Problem: After modifying an h5 file using irregular frequency removal (this process seems to work), I attempt to export the new file to h5 format. Upon hitting save, the BEMRosetta application appears to crash. The new file that is created appears in the correct folder, but cannot be opened in BEMRosetta or by other software.

"Error: Impossible to open file"

Thank you!

**Comment by izabala123** [comment]
Hello @cckimball

Thank you for reporting this problem. I think the cause is solved and now the h5 saving function is more robust.

Best regards
Iñaki

**Comment by cckimball** [comment]
Yes, works perfectly now. Thank you very much!

**Comment by izabala123** [comment]
You are welcome!
