### ISSUE TITLE
Installation of BEMRosetta

### ISSUE THREAD

**Issue by LD-Wave** [BEMRosetta/BEMRosetta#6]
Hi, 

Thank you for releasing the code. However, when I followed the steps shown on the website carefully and installed BEMRosetta, after installing the U++ compiler, I always failed to use command "umk" to comply the BEMRosetta to Arch Linux systems, or Window 7 systems. They all suggested similar errors, many ".h" files cannot be found such as Core/Core.h, zlib.h, Draw.h..... I am not sure whether you met these problems before. 

Hope you can help me with this issue. Many Thanks,

Best Regards,

Lei

**Comment by izabala123** [comment]
Hi Lei

You tell me that you have problems in both Linux and Windows. Let's start with Windows. Please confirm me that after downloading all, you run TheIDE at least once. This is important to finish the U++ library install

Iñaki

**Comment by LD-Wave** [comment]
Hi, Inaki,

Yeah as you said, I put the 2 packages 'BEMRosetta' and 'BEMRosetta.cl' to the folder 'bazaar' and used TheIDE to open them. After that, I typed the 'umk' command but it still suggested that there were errors: 'CtrlLib.h cannot be found'.

Lei

**Comment by izabala123** [comment]
Sorry Lei, I'm a little confused.
Could you send me screenshots of the error messages and the folder structure? Or a screengrab, that now is possible to be enclosed to these messages in mp4 format.
Iñaki

**Comment by LD-Wave** [comment]
![folder](https://user-images.githubusercontent.com/76063906/102639503-1119ec00-4151-11eb-91cc-e579fce7d7ee.PNG)
![problem](https://user-images.githubusercontent.com/76063906/102639512-12e3af80-4151-11eb-9719-cfbadb124b98.PNG)
These 2 images are the screenshots of the TheIDE and error messages respectively. 

Thank you a lot for your reply.

Many thanks,

Lei

**Comment by izabala123** [comment]
You are right, I've reproduced your error. I'll fix it.

**Comment by LD-Wave** [comment]
Hi, your method works! Thank you a lot for your help. 

However, later I found that it only worked up to the 7th step (7/37), and then crashed. Here is the screenshot. 

![screenshot4](https://user-images.githubusercontent.com/76063906/102675495-83aabc00-4191-11eb-83d1-2d13402a1dad.png)

![screenshot5](https://user-images.githubusercontent.com/76063906/102675500-873e4300-4191-11eb-9688-ed87f528ee94.png)


I am a freshman in the field of floating structures. I feel sorry that I have so many troubles and hope you can help me with this.

Thank you.

Lei

**Comment by izabala123** [comment]
No Lei, It's not your fault at all.  Yesterday I forgot to upload some of the changes. Please try it tomorrow after night build.

I promise that in few time the install will be easier as U++ library is being integrated in Github.

Thank you for your patience.
Iñaki

**Comment by izabala123** [comment]
It has been a few months since the implementation of this feature, so I think this issue can be closed.

**Comment by ManuelRanchodda** [comment]
Hola, alguien puede hacer de esto un instalador para windows? es decir un ejecutable donde le demos solo siguiente siguiente??

**Comment by izabala123** [comment]
Hi Manuel

In Windows you do not need an installer. The applications are portable. You just need to run BEMRosetta.exe. Probably, only the first time, Windows will ask you to allow the application to run. Binaries are [here](https://github.com/BEMRosetta/BEMRosetta/releases).

Best regards
Iñaki

Hola Manuel

En Windows no se necesita instalador, ya que BEMRosetta es una aplicación portátil. Sólo tienes que ejecutar BEMRosetta.exe. Probablemente, sólo la primera vez, Windows te pedirá que permitas la ejecución de la aplicación. Los ejecutables están [aquí](https://github.com/BEMRosetta/BEMRosetta/releases).

Saludos
Iñaki

**Comment by ManuelRanchodda** [comment]
Hola Iñaki, gracias por contestar a mi comentario, tienes toda la razón no habia leido las instrucciones, funciono de maravilla, solo que tengo problemas al generar los datos hidrodinamicos con NEMOH en WEC sim con Matlab.

Gracias

**Comment by izabala123** [comment]
Ya verás como en BEMRosetta es facil crearlos. Si tienes cualquier duda me avisas.

You will see that in BEMRosetta it is easy to create the necessary files to run Nemoh, and then convert the results into Wamit format, interactively, without the need to buy Matlab. If you have any questions, let me know.

**Comment by ManuelRanchodda** [comment]
Querido Iñaki, es posible cuadrar una conferencia donde me puedas enseñar BEMRosetta? o que puedas hacer una serie de videos en youtube desde la descarga del software, ejecucion del software, cargar una pieza en extension stl  y ver los parametros hidrodinamicos, por que creo que no lo estoy haciendo bien, es para mi trabajo de maestria, estoy trabajando en un sistema undimotriz, si es posible la videollamada te podre explicar en que consiste, o si existe la forma que podamos trabajar juntos en un articulo en esta parte en concreto. quedo atento a tu respuesta.

**Comment by izabala123** [comment]
Sin problemas. Haz un Doodle y considera horas de oficina y que mi huso horario es CET) (UTC+1).

**Comment by ManuelRanchodda** [comment]
Cordial saludo Iñaki te envió el enlace de doodle y a la vez una imagen de
los horarios disponibles, por favor si lees este correo me confirmas.

Best Regards.

https://doodle.com/meeting/participate/id/dRwzopLe
[image: imagen.png]
